# Generated by Django 5.1.7 on 2025-04-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UNI', '0002_alter_issue_issue_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('lecturer', 'Lecturer'), ('student', 'Student'), ('registrar', 'Registrar')], default='student', max_length=20),
        ),
    ]
